#!/usr/bin/env python3
"""GEO v2.1.1 HTML Renderer: responsive screen layout + A4 print layout."""
from __future__ import annotations
import argparse,csv,html,json
from pathlib import Path
from fs_utils import ensure_directory

STYLE='''
:root{--navy:#18324f;--ink:#1d2938;--muted:#66758a;--line:#d7e0ea;--soft:#f3f6fa;--paper:#fff;--bg:#edf1f5;--accent:#244f7d}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.68 -apple-system,BlinkMacSystemFont,"PingFang SC","Microsoft YaHei",sans-serif}
main{max-width:1180px;margin:24px auto;background:var(--paper);padding:52px 64px;box-shadow:0 10px 32px #00000012;border-radius:10px;overflow:hidden}
.cover{min-height:68vh;display:flex;flex-direction:column;justify-content:center}.eyebrow{letter-spacing:.16em;color:#526b86;font-size:12px}.cover h1{font-size:42px;line-height:1.18;color:var(--navy);margin:.25em 0}.cover .sub{font-size:19px;color:#43556a;max-width:850px}.meta{color:var(--muted);margin-top:22px}
.page{padding-top:18px;margin-top:34px;border-top:1px solid #eef2f6}h2{color:var(--navy);font-size:28px;line-height:1.25;margin:.2em 0 .7em}h3{color:var(--navy);font-size:18px;margin:1.1em 0 .45em}
.kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.kpi{border-top:3px solid var(--navy);background:var(--soft);padding:14px 16px;min-width:0}.kpi b{font-size:28px;color:var(--navy);display:block}.kpi span{color:var(--muted);font-size:13px}
.callout{border-left:4px solid var(--navy);background:var(--soft);padding:14px 18px;border-radius:0 6px 6px 0}.callout p{margin:.35em 0}
.chart{width:100%;max-width:100%;margin:16px 0;overflow:hidden}.chart svg{width:100%!important;max-width:100%!important;height:auto!important;display:block}.chart img{max-width:100%;height:auto}
.table-wrap{width:100%;overflow-x:auto;-webkit-overflow-scrolling:touch;border:1px solid var(--line);border-radius:6px}table{width:100%;border-collapse:collapse;font-size:13px;min-width:680px}th,td{border-bottom:1px solid var(--line);padding:9px 10px;vertical-align:top;text-align:left}th{background:#eaf0f6;color:#263d58;white-space:nowrap}tr:last-child td{border-bottom:0}.compact{min-width:620px}.appendix table{font-size:12px}
.cards{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.card{border:1px solid var(--line);border-radius:8px;padding:14px 16px;background:#fff}.card h3{margin-top:0}.metric{display:flex;gap:14px;flex-wrap:wrap;color:var(--muted);font-size:13px}.metric b{color:var(--ink)}.tag{display:inline-block;background:#eaf0f6;color:#294867;border-radius:999px;padding:2px 8px;font-size:12px;margin-right:6px}
.muted{color:var(--muted)}.note{font-size:13px;color:var(--muted)}.audit-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.audit-box{background:var(--soft);padding:12px;border-radius:6px}.asset-list{columns:2;column-gap:30px}.footer-note{margin-top:24px;font-size:12px;color:var(--muted)}
@media(max-width:860px){main{margin:0;padding:30px 20px;border-radius:0}.cover{min-height:auto;padding:48px 0}.cover h1{font-size:32px}.kpis{grid-template-columns:repeat(2,minmax(0,1fr))}.cards,.audit-grid{grid-template-columns:1fr}.asset-list{columns:1}h2{font-size:24px}}
@media print{@page{size:A4 portrait;margin:18mm 19mm}body{background:#fff;font-size:10pt}main{width:auto;max-width:none;margin:0;padding:0;box-shadow:none;border-radius:0;overflow:visible}.cover{min-height:245mm}.page{break-before:page;border-top:0;margin-top:0;padding-top:2mm}.page:first-of-type{break-before:auto}.kpis{grid-template-columns:repeat(4,1fr);gap:6px}.kpi{padding:8px}.kpi b{font-size:18pt}.cards{grid-template-columns:1fr}.card,.callout,.chart,tr{break-inside:avoid}.table-wrap{overflow:visible;border:0}table{min-width:0;font-size:8.5pt}th,td{padding:5px 5px}.chart svg{width:100%!important;height:auto!important}.asset-list{columns:2}}
'''

def esc(v):return html.escape(str(v or ""))
def read_csv(p):
    with p.open("r",encoding="utf-8-sig",newline="") as f:return list(csv.DictReader(f))
def inline_svg(path:Path):return path.read_text(encoding="utf-8") if path.is_file() else f'<div class="callout">缺少图表：{esc(path.name)}</div>'
def table(headers,rows,cls=""):
    return '<div class="table-wrap"><table class="'+cls+'"><thead><tr>'+''.join(f'<th>{esc(x)}</th>' for x in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join(f'<td>{x if isinstance(x,str) and x.startswith("<") else esc(x)}</td>' for x in row)+'</tr>' for row in rows)+'</tbody></table></div>'
def pct(v):return f"{float(v or 0)*100:.0f}%"

def render(run:Path):
    model=json.loads((run/"report_model.json").read_text(encoding="utf-8"));meta=model.get("meta",{});ev=read_csv(run/"evidence.csv");out=[]
    out.append(f'<section class="cover" data-section="cover"><div class="eyebrow">INTERNAL RESEARCH</div><h1>{esc(model.get("title"))}</h1><div class="sub">{esc(model.get("subtitle"))}</div><p class="meta">研究范围：{esc(meta.get("normalized_region") or meta.get("requested_region"))}<br>观察日期：{esc(meta.get("observation_date"))}<br>研究性质：公开互联网 GEO 竞争情报<br>采样模式：{esc(meta.get("sampling_mode","public-web-proxy"))}</p></section>')
    k=model.get("kpis",{});out.append('<section class="page" data-section="overview"><h2>研究概览</h2><div class="kpis">'+''.join(f'<div class="kpi"><b>{k.get(key,0)}</b><span>{label}</span></div>' for key,label in [("independent_institutions","独立机构候选"),("scored_institutions","正式评分机构"),("institution_measurement_queries","机构无品牌问题"),("evidence_count","可复核 Evidence")])+'</div><h2>Executive Summary</h2><div class="callout">'+''.join(f'<p>{esc(x)}</p>' for x in model.get("executive_summary",[]))+'</div></section>')
    for section,title,key in [("ranking","GEO 综合排名与市场格局","ranking"),("authority-recall","Authority × Recall 竞争矩阵","authority_recall")]:out.append(f'<section class="page" data-section="{section}"><h2>{title}</h2><div class="chart">{inline_svg(run/model["charts"][key])}</div>'+('<p class="muted">横轴为机构 Measurement Recall Rate，纵轴为 Evidence Authority Index；两者均不代表教学质量。</p>' if section=="authority-recall" else '')+'</section>')
    out.append('<section class="page" data-section="candidate-coverage"><h2>Candidate Coverage / 调研完整性</h2><div class="chart">'+inline_svg(run/model["charts"]["funnel"])+'</div><h2>五维能力结构</h2><div class="chart">'+inline_svg(run/model["charts"]["heatmap"])+'</div></section>')
    rankrows=[[r.get("rank"),r.get("institution"),r.get("total"),r.get("tier"),pct(r.get("recall_rate")),f"{r.get('authority_index',0):g}"] for r in model.get("ranking",[])];out.append('<section class="page" data-section="scorecard"><h2>商业解释型 Scorecard</h2>'+table(["排名","主体","GEO指数","Tier","Recall","Authority"],rankrows,"compact")+'<div class="cards">'+''.join(f'<article class="card"><h3>{esc(r.get("institution"))}</h3><div class="metric"><span>GEO <b>{r.get("total")}</b></span><span>Tier <b>{esc(r.get("tier"))}</b></span><span>Recall <b>{pct(r.get("recall_rate"))}</b></span><span>Authority <b>{r.get("authority_index",0):g}</b></span></div><p><span class="tag">{esc(r.get("route"))}</span></p><p><b>最强资产：</b>{esc(r.get("strongest_asset"))}</p><p><b>最大短板：</b>{esc(r.get("largest_gap"))}</p><p class="note">自有来源依赖：{pct(r.get("owned_source_dependency_ratio"))}</p></article>' for r in model.get("scorecards",[]))+'</div></section>')
    obs=model.get("observation_group",[]);obsrows=[[x.get("name"),x.get("candidate_type"),x.get("status"),"是" if x.get("user_specified") else "否","、".join(x.get("missing") or []) or "—",x.get("reason")] for x in obs];out.append('<section class="page" data-section="observation-group"><h2>本土候选观察组</h2><p class="muted">未进入正式排名不等于 GEO 为零。本区块披露 evidence-insufficient / unresolved 主体及原因，避免本土机构或 IP 静默消失。</p>'+ (table(["主体","类型","状态","用户指定","缺失项","未评分原因"],obsrows) if obsrows else '<p class="muted">本次无证据不足或未解析主体。</p>')+'</section>')
    ip=model.get("ip_measurement",{});iprows=[[x.get("rank"),x.get("teacher_name"),x.get("institution") or "—",f"{x.get('ip_hits',0)}/{x.get('ip_queries',0)}",pct(x.get("ip_recall")),x.get("subjects") or "—",x.get("platforms") or "—",x.get("evidence_confidence") or "—"] for x in ip.get("rows",[])];out.append('<section class="page" data-section="ip-expert"><h2>IP / Expert GEO</h2><p class="muted">'+esc(ip.get("note"))+'</p>'+ (table(["排名","IP / 老师","关联机构","召回","Recall","科目/标签","平台","证据置信度"],iprows) if ip.get("executed") else '<p>本次未执行 IP Measurement。</p>')+'</section>')
    qrows=[[x.get("query_id"),x.get("query_text"),x.get("theme"),x.get("matched_entities")] for x in model.get("query_occupancy",[])];out.append('<section class="page" data-section="query-gap"><h2>固定 Query 占位观察</h2>'+ (table(["Query","问题","主题","命中主体数"],qrows,"compact") if qrows else '<p class="muted">本次没有可展示的机构 Measurement Matrix。</p>')+'<h2>概念山头 / Gap Map</h2>'+(''.join(f'<p>{esc(x)}</p>' for x in model.get("concept_gaps",[])) or '<p class="muted">由弱召回、无结果、实体歧义与概念关系不稳识别；若本次未形成确定结论则不强行填充。</p>')+'</section>')
    out.append('<section class="page" data-section="strategy"><h2>区域进入策略与 90 天 GEO 工程</h2><h3>区域进入策略</h3>'+(''.join(f'<p>{esc(x)}</p>' for x in model.get("entry_strategy",[])) or '<p class="muted">由本次 Gap 与竞争路线分析生成。</p>')+'<h3>90 天 GEO 内容与知识资产工程</h3>'+(''.join(f'<p>{esc(x)}</p>' for x in model.get("plan_90_days",[])) or '<p class="muted">阶段建议需与本次实际 Gap 强关联。</p>')+'<h3>月度监测看板</h3>'+(''.join(f'<p>{esc(x)}</p>' for x in model.get("monthly_dashboard",[])) or '<p class="muted">核心 KPI：无品牌召回率、首提率、引用率、正确实体率、可引用 Evidence 数、概念绑定稳定度、错误信息率。</p>')+'</section>')
    app=model.get("appendix",{});audit=app.get("research_audit",{});status=app.get("candidate_status",{});out.append('<section class="page appendix" data-section="appendix-audit"><h2>Appendix / Research Audit</h2><div class="audit-grid"><div class="audit-box"><b>运行信息</b><p>Schema版本：'+esc(model.get("schema_version","2.1.1"))+'<br>Skill版本：'+esc(meta.get("skill_version","2.1.1"))+'<br>采样模式：'+esc(audit.get("sampling_mode"))+'</p></div><div class="audit-box"><b>Candidate Status</b><p>'+('<br>'.join(f'{esc(k)}: {v}' for k,v in sorted(status.items())) or '—')+'</p></div><div class="audit-box"><b>Freeze Gates</b><p>Semantic Coverage: '+esc(audit.get("semantic_coverage_gate"))+'<br>Saturation: '+esc(audit.get("saturation_gate"))+'<br>Local Ecosystem: '+esc(audit.get("local_ecosystem_gate"))+'<br>Candidate Frozen: '+esc(audit.get("candidate_pool_frozen"))+'</p></div><div class="audit-box"><b>Research Counts</b><p>Coverage rows: '+esc(audit.get("coverage_rows"))+'<br>Institution Measurement: '+esc(audit.get("institution_measurement_queries"))+'<br>IP Measurement: '+esc(audit.get("ip_measurement_queries"))+'<br>Evidence: '+esc(audit.get("evidence_count"))+'</p></div></div><h3>Research Assets</h3><div class="asset-list">'+''.join(f'<div>• {esc(x)}</div>' for x in app.get("research_assets",[]))+'</div><h3>Evidence Index</h3>'+table(["ID","主体","来源","Grade","日期"],[[r.get("evidence_id"),r.get("institution"),f'<a href="{esc(r.get("source_url"))}">{esc(r.get("source_title"))}</a>',r.get("source_grade"),r.get("published_date")] for r in ev])+'<p class="footer-note">GEO观察指数衡量公开网络与 AI 可利用资产结构，不代表教学水平、市场份额、上岸率或大模型官方推荐。</p></section>')
    title=esc(model.get("title","GEO Report"));return f'<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title}</title><style>{STYLE}</style></head><body><main>{"".join(out)}</main></body></html>'

def main():
    p=argparse.ArgumentParser();p.add_argument("run_dir",type=Path);p.add_argument("--output",type=Path);a=p.parse_args();out=a.output or a.run_dir/"deliverables"/"report.html";ensure_directory(out.parent);out.write_text(render(a.run_dir),encoding="utf-8");print(out);return 0
if __name__=="__main__":raise SystemExit(main())
