#!/usr/bin/env python3
"""v2.1 HTML Renderer：只从统一 Report Model 与本次 Run 图表生成正式 HTML。"""
from __future__ import annotations
import argparse,csv,html,json
from pathlib import Path
STYLE='''
:root{--navy:#18324f;--ink:#1d2938;--muted:#66758a;--line:#d7e0ea;--soft:#f3f6fa}
*{box-sizing:border-box}body{margin:0;background:#edf1f5;color:var(--ink);font:15px/1.65 -apple-system,BlinkMacSystemFont,"PingFang SC","Microsoft YaHei",sans-serif}main{width:210mm;min-height:297mm;margin:18px auto;background:white;padding:20mm 19mm;box-shadow:0 8px 28px #0001}.cover{min-height:245mm;display:flex;flex-direction:column;justify-content:center}.eyebrow{letter-spacing:.16em;color:#526b86}.cover h1{font-size:32pt;line-height:1.18;color:var(--navy);margin:.25em 0}.cover .sub{font-size:14pt;color:#43556a}.kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.kpi{border-top:3px solid var(--navy);background:var(--soft);padding:12px}.kpi b{font-size:24px;color:var(--navy);display:block}.page{break-before:page;padding-top:2mm}h2{color:var(--navy);font-size:20pt;margin:.2em 0 .65em}h3{color:var(--navy)}.callout{border-left:4px solid var(--navy);background:var(--soft);padding:12px 16px}.chart{width:100%;margin:12px 0;break-inside:avoid}table{width:100%;border-collapse:collapse;font-size:9.5pt}th,td{border-bottom:1px solid var(--line);padding:7px 6px;vertical-align:top}th{background:#eaf0f6;color:#263d58;text-align:left}.muted{color:var(--muted)}.appendix{font-size:9pt}.evidence a{color:#244f7d}.footer-note{margin-top:24px;font-size:8.5pt;color:var(--muted)}@page{size:A4 portrait;margin:18mm 19mm}@media print{body{background:white}main{width:auto;min-height:0;margin:0;padding:0;box-shadow:none}.page{break-before:page}.cover{min-height:245mm}table{font-size:9pt}tr,img,.chart,.kpi{break-inside:avoid}}
'''
def esc(v):return html.escape(str(v or ""))
def read_csv(p):
    with p.open("r",encoding="utf-8-sig",newline="") as f:return list(csv.DictReader(f))
def inline_svg(path:Path):return path.read_text(encoding="utf-8") if path.is_file() else f'<div class="callout">缺少图表：{esc(path.name)}</div>'
def render(run:Path):
    model=json.loads((run/"report_model.json").read_text(encoding="utf-8"));meta=model.get("meta",{});ev=read_csv(run/"evidence.csv");out=[]
    out.append(f'<section class="cover"><div class="eyebrow">INTERNAL RESEARCH</div><h1>{esc(model.get("title"))}</h1><div class="sub">{esc(model.get("subtitle"))}</div><p>研究范围：{esc(meta.get("normalized_region") or meta.get("requested_region"))}<br>观察日期：{esc(meta.get("observation_date"))}<br>研究性质：公开互联网 GEO 竞争情报</p></section>')
    k=model.get("kpis",{});out.append('<section class="page"><h2>研究概览</h2><div class="kpis">'+''.join(f'<div class="kpi"><b>{k.get(key,0)}</b>{label}</div>' for key,label in [("independent_institutions","独立机构候选"),("scored_institutions","正式评分机构"),("institution_measurement_queries","无品牌问题实测"),("evidence_count","可复核 Evidence")])+'</div><h2>Executive Summary</h2><div class="callout">'+''.join(f'<p>{esc(x)}</p>' for x in model.get("executive_summary",[]))+'</div></section>')
    out.append('<section class="page"><h2>GEO 综合排名与市场格局</h2><div class="chart">'+inline_svg(run/model["charts"]["ranking"])+'</div></section>')
    out.append('<section class="page"><h2>Authority × Recall 竞争矩阵</h2><div class="chart">'+inline_svg(run/model["charts"]["authority_recall"])+'</div><p class="muted">横轴为机构 Measurement Recall Rate，纵轴为 Evidence Authority Index，两者与教学质量无关。</p></section>')
    out.append('<section class="page"><h2>Candidate Coverage / 调研完整性</h2><div class="chart">'+inline_svg(run/model["charts"]["funnel"])+'</div><h2>五维能力结构</h2><div class="chart">'+inline_svg(run/model["charts"]["heatmap"])+'</div></section>')
    rows=model.get("scorecards",[]);out.append('<section class="page"><h2>商业解释型 Scorecard</h2><table><thead><tr><th>排名</th><th>主体</th><th>GEO指数</th><th>Tier</th><th>竞争路线</th><th>最强资产</th><th>最大短板</th></tr></thead><tbody>'+''.join(f'<tr><td>{i+1}</td><td>{esc(r.get("institution"))}</td><td>{r.get("total")}</td><td>{esc(r.get("tier"))}</td><td>{esc(r.get("route"))}</td><td>{esc(r.get("strongest_asset"))}</td><td>{esc(r.get("largest_gap"))}</td></tr>' for i,r in enumerate(rows))+'</tbody></table></section>')
    out.append('<section class="page"><h2>重点机构诊断</h2>'+(''.join(f'<div class="callout"><h3>{esc(x.get("institution") or x.get("name") or "机构诊断")}</h3><p>{esc(x.get("summary") or x)}</p></div>' for x in model.get("diagnoses",[]) if isinstance(x,dict)) or '<p class="muted">重点机构诊断由本次 Score、Recall、Authority 与 Evidence 归纳。</p>')+'<h2>IP / Expert GEO</h2><p class="muted">'+('本次已执行 IP Measurement。' if model.get("kpis",{}).get("ip_measurement_queries",0) else '本次未执行 IP Measurement，仅作 IP 实体 / 专家可见性观察。')+'</p></section>')
    out.append('<section class="page"><h2>固定 Query 占位观察</h2>'+(''.join(f'<p>{esc(x)}</p>' for x in model.get("query_occupancy",[])) or '<p class="muted">由 Institution Measurement Matrix 转译。</p>')+'<h2>概念山头 / Gap Map</h2>'+(''.join(f'<p>{esc(x)}</p>' for x in model.get("concept_gaps",[])) or '<p class="muted">由无结果、弱召回、实体歧义与概念关系不稳识别。</p>')+'<h2>竞争路线</h2><p class="muted">竞争路线由本次资产结构自动归纳，不参与评分。</p></section>')
    out.append('<section class="page"><h2>区域进入策略与 90 天 GEO 工程</h2><h3>区域进入策略</h3>'+(''.join(f'<p>{esc(x)}</p>' for x in model.get("entry_strategy",[])) or '<p class="muted">由本次 Gap 与竞争路线分析生成。</p>')+'<h3>90 天 GEO 内容与知识资产工程</h3>'+(''.join(f'<p>{esc(x)}</p>' for x in model.get("plan_90_days",[])) or '<p class="muted">阶段建议需与本次实际 Gap 强关联。</p>')+'<h3>月度监测看板</h3>'+(''.join(f'<p>{esc(x)}</p>' for x in model.get("monthly_dashboard",[])) or '<p class="muted">核心 KPI：无品牌召回率、首提率、引用率、正确实体率、可引用 Evidence 数、概念绑定稳定度、错误信息率。</p>')+'</section>')
    out.append('<section class="page appendix"><h2>Appendix / Research Audit</h2><p>Schema版本：2.1<br>Skill版本：2.1<br>采样模式：'+esc(meta.get("sampling_mode","public-web-proxy"))+'</p><h3>Evidence Index</h3><table class="evidence"><thead><tr><th>ID</th><th>主体</th><th>来源</th><th>Grade</th><th>日期</th></tr></thead><tbody>'+''.join(f'<tr id="evidence-{esc(r.get("evidence_id"))}"><td>{esc(r.get("evidence_id"))}</td><td>{esc(r.get("institution"))}</td><td><a href="{esc(r.get("source_url"))}">{esc(r.get("source_title"))}</a></td><td>{esc(r.get("source_grade"))}</td><td>{esc(r.get("published_date"))}</td></tr>' for r in ev)+'</tbody></table><p class="footer-note">GEO观察指数衡量公开网络与 AI 可利用资产结构，不代表教学水平、市场份额、上岸率或大模型官方推荐。</p></section>')
    title=esc(model.get("title","GEO Report"));return f'<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title}</title><style>{STYLE}</style></head><body><main>{"".join(out)}</main></body></html>'
def main():
    p=argparse.ArgumentParser();p.add_argument("run_dir",type=Path);p.add_argument("--output",type=Path);a=p.parse_args();out=a.output or a.run_dir/"deliverables"/"report.html";out.parent.mkdir(exist_ok=True);out.write_text(render(a.run_dir),encoding="utf-8");print(out);return 0
if __name__=="__main__":raise SystemExit(main())
