#!/usr/bin/env python3
"""v2.1 行为回归：17项核心门禁与 Renderer 纪律。"""
from __future__ import annotations
import csv,importlib.util,json,shutil,sys,tempfile
from pathlib import Path
HERE=Path(__file__).resolve().parent

def load(name,file):
    spec=importlib.util.spec_from_file_location(name,HERE/file);m=importlib.util.module_from_spec(spec);sys.modules[name]=m;spec.loader.exec_module(m);return m
pre=load('preflight_v21','preflight.py');charts=load('charts_v21','generate_charts.py');modeler=load('model_v21','build_report_model.py');validator=load('validator_v21','validate_run.py');scorer=load('scorer_v21','score_geo.py');htmlr=load('html_v21','generate_report_html.py');docxr=load('docx_v21','generate_report_docx.py');pdfr=load('pdf_v21','generate_report_pdf.py')

def wcsv(p,fields,rows):
    with p.open('w',encoding='utf-8',newline='') as f:wr=csv.DictWriter(f,fieldnames=fields);wr.writeheader();wr.writerows(rows)
def rcsv(p):
    with p.open('r',encoding='utf-8-sig',newline='') as f:return list(csv.DictReader(f))
def build(run:Path,fmt='docx'):
    meta=pre.make_metadata('示例省',[],[fmt],entities_decided=True);meta.update({'observation_date':'2026-09-09','sampling_mode':'public-web-proxy','research_mode':'regional-landscape','semantic_coverage_gate':True,'saturation_gate':True,'candidate_pool_frozen':True,'run_status':'frozen','consecutive_no_important_new_rounds':0});(run/'run_metadata.json').write_text(json.dumps(meta,ensure_ascii=False,indent=2),encoding='utf-8')
    qf=['query_id','query_text','query_type','query_purpose','measurement_target','discovery_channel','discovery_round','semantic_theme','theme','region','city','exam','sampled_channel','sampled_at','status','notes'];qs=[];channels=['user-query','exam-vertical','institutional','platform','expert-ip','entity-alias']
    for i,ch in enumerate(channels,1):qs.append({'query_id':f'QD{i}','query_text':f'示例省 {ch}','query_type':'generic','query_purpose':'discovery','measurement_target':'','discovery_channel':ch,'discovery_round':'1' if i<=3 else '2','semantic_theme':ch,'theme':'发现','region':'示例省','city':'','exam':'省考','sampled_channel':'public-web','sampled_at':'2026-09-09T10:00:00+08:00','status':'sampled','notes':''})
    qs += [
      {'query_id':'QD7','query_text':'示例省补漏','query_type':'generic','query_purpose':'discovery','measurement_target':'','discovery_channel':'institutional','discovery_round':'3','semantic_theme':'补漏','theme':'补漏','region':'示例省','city':'','exam':'省考','sampled_channel':'public-web','sampled_at':'2026-09-09T10:10:00+08:00','status':'sampled','notes':''},
      {'query_id':'QM1','query_text':'示例省公考机构有哪些','query_type':'generic','query_purpose':'measurement','measurement_target':'institution','discovery_channel':'','discovery_round':'','semantic_theme':'','theme':'综合','region':'示例省','city':'','exam':'省考','sampled_channel':'public-web','sampled_at':'2026-09-09T10:20:00+08:00','status':'sampled','notes':''},
      {'query_id':'QM2','query_text':'示例省公考面试机构','query_type':'generic','query_purpose':'measurement','measurement_target':'institution','discovery_channel':'','discovery_round':'','semantic_theme':'','theme':'面试','region':'示例省','city':'','exam':'省考','sampled_channel':'public-web','sampled_at':'2026-09-09T10:21:00+08:00','status':'sampled','notes':''},
      {'query_id':'QIP1','query_text':'示例省申论老师推荐','query_type':'generic','query_purpose':'measurement','measurement_target':'ip','discovery_channel':'','discovery_round':'','semantic_theme':'','theme':'IP','region':'示例省','city':'','exam':'省考','sampled_channel':'public-web','sampled_at':'2026-09-09T10:22:00+08:00','status':'sampled','notes':''},
      {'query_id':'QV1','query_text':'甲机构官网','query_type':'brand','query_purpose':'verification','measurement_target':'','discovery_channel':'','discovery_round':'','semantic_theme':'','theme':'核验','region':'示例省','city':'','exam':'省考','sampled_channel':'public-web','sampled_at':'2026-09-09T10:23:00+08:00','status':'sampled','notes':''},
      {'query_id':'QV2','query_text':'乙机构官网','query_type':'brand','query_purpose':'verification','measurement_target':'','discovery_channel':'','discovery_round':'','semantic_theme':'','theme':'核验','region':'示例省','city':'','exam':'省考','sampled_channel':'public-web','sampled_at':'2026-09-09T10:24:00+08:00','status':'sampled','notes':''}]
    wcsv(run/'queries.csv',qf,qs)
    rf=['result_id','query_id','entity_id','result_rank','source_url','source_title','matched_name','observed_at','channel','matched','counts_as_measurement_hit','notes'];rs=[
      {'result_id':'R1','query_id':'QD1','entity_id':'I1','result_rank':1,'source_url':'https://a.example/discovery','source_title':'发现','matched_name':'甲机构','observed_at':'2026-09-09','channel':'web','matched':'true','counts_as_measurement_hit':'false','notes':''},
      {'result_id':'R2','query_id':'QD3','entity_id':'I2','result_rank':1,'source_url':'https://b.example/discovery','source_title':'发现','matched_name':'乙机构','observed_at':'2026-09-09','channel':'web','matched':'true','counts_as_measurement_hit':'false','notes':''},
      {'result_id':'R3','query_id':'QM1','entity_id':'I1','result_rank':1,'source_url':'https://x.example/q','source_title':'测量','matched_name':'甲机构','observed_at':'2026-09-09','channel':'web','matched':'true','counts_as_measurement_hit':'true','notes':''},
      {'result_id':'R4','query_id':'QM2','entity_id':'I2','result_rank':1,'source_url':'https://y.example/q','source_title':'测量','matched_name':'乙机构','observed_at':'2026-09-09','channel':'web','matched':'true','counts_as_measurement_hit':'true','notes':''},
      {'result_id':'R5','query_id':'QIP1','entity_id':'T1','result_rank':1,'source_url':'https://z.example/ip','source_title':'IP测量','matched_name':'示例老师','observed_at':'2026-09-09','channel':'web','matched':'true','counts_as_measurement_hit':'true','notes':''},
      {'result_id':'R6','query_id':'QV1','entity_id':'I1','result_rank':1,'source_url':'https://a.example/about','source_title':'甲官网','matched_name':'甲机构','observed_at':'2026-09-09','channel':'web','matched':'true','counts_as_measurement_hit':'false','notes':''},
      {'result_id':'R7','query_id':'QV2','entity_id':'I2','result_rank':1,'source_url':'https://b.example/about','source_title':'乙官网','matched_name':'乙机构','observed_at':'2026-09-09','channel':'web','matched':'true','counts_as_measurement_hit':'false','notes':''}]
    wcsv(run/'query_results.csv',rf,rs)
    covf=['region','discovery_channel','semantic_theme','required','query_count','result_count','eligible_candidates_found','status','notes'];wcsv(run/'discovery_coverage.csv',covf,[{'region':'示例省','discovery_channel':ch,'semantic_theme':ch,'required':'true','query_count':1,'result_count':1,'eligible_candidates_found':1 if ch in {'user-query','institutional'} else 0,'status':'covered','notes':''} for ch in channels]+[{'region':'示例省','discovery_channel':'institutional','semantic_theme':'补漏','required':'true','query_count':1,'result_count':0,'eligible_candidates_found':0,'status':'no-result-reviewed','notes':''}])
    ef=['entity_id','canonical_name','entity_type','aliases','legal_name','former_names','brand_name','official_domain','official_account','region','parent_entity_id','entity_status','disambiguation_notes','source_ids','notes'];wcsv(run/'entities.csv',ef,[{'entity_id':'I1','canonical_name':'甲机构','entity_type':'institution','aliases':'甲公考','legal_name':'甲教育有限公司','former_names':'','brand_name':'甲机构','official_domain':'a.example','official_account':'','region':'示例省','parent_entity_id':'','entity_status':'active','disambiguation_notes':'','source_ids':'E1|E2','notes':''},{'entity_id':'I2','canonical_name':'乙机构','entity_type':'institution','aliases':'乙公考','legal_name':'乙教育有限公司','former_names':'','brand_name':'乙机构','official_domain':'b.example','official_account':'','region':'示例省','parent_entity_id':'','entity_status':'active','disambiguation_notes':'','source_ids':'E3|E4','notes':''},{'entity_id':'T1','canonical_name':'示例老师','entity_type':'teacher','aliases':'','legal_name':'','former_names':'','brand_name':'','official_domain':'','official_account':'','region':'示例省','parent_entity_id':'','entity_status':'active','disambiguation_notes':'','source_ids':'E5','notes':''}])
    cf=['candidate_id','entity_id','display_name','candidate_type','discovery_round','discovery_channel','discovery_query_id','discovery_result_id','first_seen_at','evidence_strength','user_specified','status','merged_into_entity_id','exclusion_reason','notes'];wcsv(run/'candidate_pool.csv',cf,[{'candidate_id':'C1','entity_id':'I1','display_name':'甲机构','candidate_type':'institution','discovery_round':'1','discovery_channel':'user-query','discovery_query_id':'QD1','discovery_result_id':'R1','first_seen_at':'2026-09-09','evidence_strength':'high','user_specified':'false','status':'scored','merged_into_entity_id':'','exclusion_reason':'','notes':''},{'candidate_id':'C2','entity_id':'I2','display_name':'乙机构','candidate_type':'institution','discovery_round':'1','discovery_channel':'institutional','discovery_query_id':'QD3','discovery_result_id':'R2','first_seen_at':'2026-09-09','evidence_strength':'high','user_specified':'false','status':'scored','merged_into_entity_id':'','exclusion_reason':'','notes':''}])
    evf=['evidence_id','entity_id','institution','query_id','query','query_type','source_title','source_url','source_domain','published_date','accessed_date','source_grade','independent','claim_type','concepts','duplicate_group','duplicate_reason','review_status','counting_scope','notes'];wcsv(run/'evidence.csv',evf,[{'evidence_id':'E1','entity_id':'I1','institution':'甲机构','query_id':'QV1','query':'甲官网','query_type':'brand','source_title':'甲官网','source_url':'https://a.example/about','source_domain':'a.example','published_date':'2026-08-01','accessed_date':'2026-09-09','source_grade':'A2','independent':'false','claim_type':'institution-claim','concepts':'[]','duplicate_group':'','duplicate_reason':'','review_status':'','counting_scope':'entity','notes':''},{'evidence_id':'E2','entity_id':'I1','institution':'甲机构','query_id':'QD3','query':'机构性','query_type':'generic','source_title':'高校活动','source_url':'https://edu.example/a','source_domain':'edu.example','published_date':'2026-07-01','accessed_date':'2026-09-09','source_grade':'A1','independent':'true','claim_type':'fact','concepts':'[]','duplicate_group':'','duplicate_reason':'','review_status':'','counting_scope':'entity','notes':''},{'evidence_id':'E3','entity_id':'I2','institution':'乙机构','query_id':'QV2','query':'乙官网','query_type':'brand','source_title':'乙官网','source_url':'https://b.example/about','source_domain':'b.example','published_date':'2026-08-01','accessed_date':'2026-09-09','source_grade':'A2','independent':'false','claim_type':'institution-claim','concepts':'[]','duplicate_group':'','duplicate_reason':'','review_status':'','counting_scope':'entity','notes':''},{'evidence_id':'E4','entity_id':'I2','institution':'乙机构','query_id':'QD2','query':'垂类','query_type':'generic','source_title':'第三方','source_url':'https://third.example/b','source_domain':'third.example','published_date':'2026-06-01','accessed_date':'2026-09-09','source_grade':'B','independent':'true','claim_type':'fact','concepts':'[]','duplicate_group':'','duplicate_reason':'','review_status':'','counting_scope':'entity','notes':''},{'evidence_id':'E5','entity_id':'T1','institution':'甲机构','query_id':'QIP1','query':'老师','query_type':'generic','source_title':'老师页','source_url':'https://a.example/teacher','source_domain':'a.example','published_date':'2026-08-05','accessed_date':'2026-09-09','source_grade':'A2','independent':'false','claim_type':'institution-claim','concepts':'[]','duplicate_group':'','duplicate_reason':'','review_status':'','counting_scope':'entity','notes':''}])
    relf=['relation_id','source_entity_id','relation_type','target_entity_id','relation_status','valid_from','valid_to','evidence_ids','confidence','notes'];wcsv(run/'entity_relations.csv',relf,[{'relation_id':'REL1','source_entity_id':'T1','relation_type':'teaches-at','target_entity_id':'I1','relation_status':'current','valid_from':'2026','valid_to':'','evidence_ids':'E5','confidence':'Medium','notes':''}])
    sf=['institution','entity_id','inclusion_basis','query_coverage','entity_clarity','external_diversity','concept_ownership','freshness','total','tier','evidence_confidence','generic_hits','generic_queries','brand_hits','evidence_count','independent_domains','authority_index','competition_route','notes'];wcsv(run/'scores.csv',sf,[{'institution':'甲机构','entity_id':'I1','inclusion_basis':'discovered','query_coverage':12,'entity_clarity':18,'external_diversity':10,'concept_ownership':8,'freshness':8,'total':56,'tier':'B','evidence_confidence':'Medium','generic_hits':1,'generic_queries':2,'brand_hits':1,'evidence_count':2,'independent_domains':1,'authority_index':55,'competition_route':'高权威低召回型','notes':''},{'institution':'乙机构','entity_id':'I2','inclusion_basis':'discovered','query_coverage':12,'entity_clarity':16,'external_diversity':9,'concept_ownership':7,'freshness':7,'total':51,'tier':'B','evidence_confidence':'Medium','generic_hits':1,'generic_queries':2,'brand_hits':1,'evidence_count':2,'independent_domains':1,'authority_index':48,'competition_route':'本地实体型','notes':''}])
    dims=lambda q,e:{'query_coverage':{'score':12,'reason':'1/2机构Measurement命中','query_ids':[q]},'entity_clarity':{'score':18 if e=='E1' else 16,'reason':'主体可确认','evidence_ids':[e]},'external_diversity':{'score':10 if e=='E1' else 9,'reason':'存在独立来源','evidence_ids':['E2' if e=='E1' else 'E4']},'concept_ownership':{'score':8 if e=='E1' else 7,'reason':'概念关联有限','evidence_ids':[e]},'freshness':{'score':8 if e=='E1' else 7,'reason':'近一年有更新','evidence_ids':[e]}}
    (run/'score_details.json').write_text(json.dumps([{'entity_id':'I1','dimensions':dims('QM1','E1')},{'entity_id':'I2','dimensions':dims('QM2','E3')}],ensure_ascii=False,indent=2),encoding='utf-8')
    ipf=['teacher_name','entity_id','aliases','institution','relation_status','relation_period','subjects','products','regions','platforms','ip_hits','ip_queries','ip_recall','entity_confidence','institution_relation','subject_binding','concept_ownership','evidence_health','brand_hits','source_ids','evidence_confidence','notes'];wcsv(run/'ip_entities.csv',ipf,[{'teacher_name':'示例老师','entity_id':'T1','aliases':'','institution':'甲机构','relation_status':'current','relation_period':'2026','subjects':'申论','products':'课程','regions':'示例省','platforms':'官网','ip_hits':1,'ip_queries':1,'ip_recall':1.0,'entity_confidence':'Medium','institution_relation':'confirmed','subject_binding':'Medium','concept_ownership':'Low','evidence_health':'Medium','brand_hits':0,'source_ids':'E5','evidence_confidence':'Medium','notes':''}])
    charts.generate(run);modeler.build(run)
    if fmt=='docx':docxr.render(run,run/'deliverables'/'report.docx')
    elif fmt=='pdf':pdfr.render(run,run/'deliverables'/'report.pdf')
    else:
        p=run/'deliverables'/'report.html';p.parent.mkdir(exist_ok=True);p.write_text(htmlr.render(run),encoding='utf-8')

def codes(run):return {x.code for x in validator.validate(run) if x.level in {'error','warning'}}
def clone(src,dst):shutil.copytree(src,dst)
def main():
    passed=[]
    with tempfile.TemporaryDirectory(prefix='geo-v21-') as td:
        base=Path(td)/'base';base.mkdir();build(base,'docx');assert not codes(base);passed.append('01-valid-v21')
        assert pre.missing_questions(pre.make_metadata(None,None,None))==['region'];passed.append('02-preflight-missing')
        assert pre.missing_questions(pre.make_metadata('天津',['津仕','北宋'],None))==['output_format'];passed.append('03-preflight-no-repeat')
        t=Path(td)/'t4';clone(base,t);r=rcsv(t/'query_results.csv');r[0]['counts_as_measurement_hit']='true';wcsv(t/'query_results.csv',list(r[0]),r);assert 'measurement-isolation' in codes(t);passed.append('04-discovery-not-recall')
        t=Path(td)/'t5';clone(base,t);r=rcsv(t/'query_results.csv');r[-1]['counts_as_measurement_hit']='true';wcsv(t/'query_results.csv',list(r[0]),r);assert 'measurement-isolation' in codes(t);passed.append('05-verification-not-recall')
        t=Path(td)/'t6';clone(base,t);r=rcsv(t/'discovery_coverage.csv');r[0]['status']='missing';wcsv(t/'discovery_coverage.csv',list(r[0]),r);assert 'semantic-coverage-gate' in codes(t);passed.append('06-semantic-gate')
        t=Path(td)/'t7';clone(base,t);m=json.loads((t/'run_metadata.json').read_text());m['saturation_gate']=False;(t/'run_metadata.json').write_text(json.dumps(m));assert 'saturation-metadata' in codes(t);passed.append('07-saturation-gate')
        t=Path(td)/'t8';clone(base,t);m=json.loads((t/'run_metadata.json').read_text());m['requested_entities']=['甲机构'];(t/'run_metadata.json').write_text(json.dumps(m));r=rcsv(t/'candidate_pool.csv');r[0]['user_specified']='true';wcsv(t/'candidate_pool.csv',list(r[0]),r);s=rcsv(t/'scores.csv');before=s[0]['total'];s[0]['inclusion_basis']='user-requested';wcsv(t/'scores.csv',list(s[0]),s);assert s[0]['total']==before;passed.append('08-user-specified-no-bonus')
        t=Path(td)/'t9';clone(base,t);m=json.loads((t/'run_metadata.json').read_text());m['requested_entities']=['甲机构'];(t/'run_metadata.json').write_text(json.dumps(m));r=rcsv(t/'candidate_pool.csv');r[0]['user_specified']='true';r[0]['status']='excluded';wcsv(t/'candidate_pool.csv',list(r[0]),r);assert 'user-specified-disappeared' in codes(t);passed.append('09-user-specified-visible')
        t=Path(td)/'t10';clone(base,t);mo=json.loads((t/'report_model.json').read_text());mo['kpis']['evidence_count']=99;(t/'report_model.json').write_text(json.dumps(mo));assert 'report-data-mismatch' in codes(t);passed.append('10-report-data-consistency')
        t=Path(td)/'t11';clone(base,t);cd=json.loads((t/'charts'/'chart_data.json').read_text());cd['ranking'][0]['total']=99;(t/'charts'/'chart_data.json').write_text(json.dumps(cd));assert 'chart-score-mismatch' in codes(t);passed.append('11-chart-data-consistency')
        assert scorer.score_record({'query_coverage':24,'entity_clarity':20,'external_diversity':13,'concept_ownership':11,'freshness':8})['total']==76;passed.append('12-five-dimension-stable')
        t=Path(td)/'t13';clone(base,t);r=rcsv(t/'ip_entities.csv');r[0]['ip_queries']='2';wcsv(t/'ip_entities.csv',list(r[0]),r);assert 'ip-query-denominator-mismatch' in codes(t);passed.append('13-ip-separate')
        for idx,fmt in enumerate(['docx','pdf','html'],14):
            t=Path(td)/f't{idx}';t.mkdir();build(t,fmt);assert not codes(t);found={p.suffix.lstrip('.') for p in (t/'deliverables').iterdir()};assert found=={fmt};passed.append(f'{idx:02d}-single-{fmt}')
        t=Path(td)/'t17';clone(base,t);m=json.loads((t/'run_metadata.json').read_text());m['requested_output_format']=['docx','pdf'];(t/'run_metadata.json').write_text(json.dumps(m));pdfr.render(t,t/'deliverables'/'report.pdf');assert not codes(t);assert {p.suffix.lstrip('.') for p in (t/'deliverables').iterdir()}=={'docx','pdf'};passed.append('17-multi-only-requested')
    print(f'v2.1 行为测试：通过 {len(passed)} 项');[print('- '+x) for x in passed];return 0
if __name__=='__main__':raise SystemExit(main())
