#!/usr/bin/env python3
"""GEO v2.1.1 regression: pipeline, recall completeness, report contract and HTML layout."""
from __future__ import annotations
import csv,importlib.util,json,sys,tempfile
from pathlib import Path

HERE=Path(__file__).resolve().parent

def load(name,file):
    spec=importlib.util.spec_from_file_location(name,HERE/file);m=importlib.util.module_from_spec(spec);assert spec and spec.loader;sys.modules[name]=m;spec.loader.exec_module(m);return m
pre=load('pre_v211','preflight.py');scorer=load('score_v211','score_geo.py');charts=load('charts_v211','generate_charts.py');modeler=load('model_v211','build_report_model.py');htmlr=load('html_v211','generate_report_html.py');docxr=load('docx_v211','generate_report_docx.py');pdfr=load('pdf_v211','generate_report_pdf.py');validator=load('validator_v211','validate_run.py')

def wcsv(p,fields,rows):
    with p.open('w',encoding='utf-8',newline='') as f:w=csv.DictWriter(f,fieldnames=fields);w.writeheader();w.writerows(rows)
def rcsv(p):
    with p.open('r',encoding='utf-8-sig',newline='') as f:return list(csv.DictReader(f))

def build(run:Path,fmt='html'):
    (run/'charts').mkdir(parents=True,exist_ok=True);(run/'deliverables').mkdir(parents=True,exist_ok=True)
    meta=pre.make_metadata('示例省',[],[fmt],entities_decided=True);meta.update({'observation_date':'2026-09-09','sampling_mode':'public-web-proxy','research_mode':'regional-landscape','semantic_coverage_gate':True,'saturation_gate':True,'local_ecosystem_gate':True,'candidate_pool_frozen':True,'run_status':'frozen','consecutive_no_important_new_rounds':2});(run/'run_metadata.json').write_text(json.dumps(meta,ensure_ascii=False,indent=2),encoding='utf-8')
    qf=['query_id','query_text','query_type','query_purpose','measurement_target','discovery_channel','discovery_round','semantic_theme','theme','region','city','exam','sampled_channel','sampled_at','status','notes'];qs=[];channels=['user-query','exam-vertical','institutional','platform','expert-ip','entity-alias']
    for i,ch in enumerate(channels,1):qs.append({'query_id':f'QD{i}','query_text':f'示例省 {ch}','query_type':'generic','query_purpose':'discovery','measurement_target':'','discovery_channel':ch,'discovery_round':'1' if i<=3 else '2','semantic_theme':ch,'theme':'发现','region':'示例省','city':'','exam':'省考','sampled_channel':'public-web','sampled_at':'2026-09-09','status':'sampled','notes':''})
    qs += [
      {'query_id':'QD7','query_text':'示例省 本土公考机构','query_type':'generic','query_purpose':'discovery','measurement_target':'','discovery_channel':'user-query','discovery_round':'3','semantic_theme':'local-institution-ecosystem','theme':'本土机构','region':'示例省','city':'','exam':'省考','sampled_channel':'public-web','sampled_at':'2026-09-09','status':'sampled','notes':''},
      {'query_id':'QD8','query_text':'示例省 公考老师 博主','query_type':'generic','query_purpose':'discovery','measurement_target':'','discovery_channel':'expert-ip','discovery_round':'3','semantic_theme':'local-expert-ip','theme':'本土IP','region':'示例省','city':'','exam':'省考','sampled_channel':'public-web','sampled_at':'2026-09-09','status':'sampled','notes':''},
      {'query_id':'QD9','query_text':'示例省 抖音 视频号 公考','query_type':'generic','query_purpose':'discovery','measurement_target':'','discovery_channel':'platform','discovery_round':'3','semantic_theme':'platform-native-ip','theme':'平台IP','region':'示例省','city':'','exam':'省考','sampled_channel':'public-web','sampled_at':'2026-09-09','status':'sampled','notes':''},
      {'query_id':'QM1','query_text':'示例省公考机构有哪些','query_type':'generic','query_purpose':'measurement','measurement_target':'institution','discovery_channel':'','discovery_round':'','semantic_theme':'','theme':'综合','region':'示例省','city':'','exam':'省考','sampled_channel':'public-web','sampled_at':'2026-09-09','status':'sampled','notes':''},
      {'query_id':'QM2','query_text':'示例省公考面试机构','query_type':'generic','query_purpose':'measurement','measurement_target':'institution','discovery_channel':'','discovery_round':'','semantic_theme':'','theme':'面试','region':'示例省','city':'','exam':'省考','sampled_channel':'public-web','sampled_at':'2026-09-09','status':'sampled','notes':''},
      {'query_id':'QIP1','query_text':'示例省公考规划老师推荐','query_type':'generic','query_purpose':'measurement','measurement_target':'ip','discovery_channel':'','discovery_round':'','semantic_theme':'','theme':'规划IP','region':'示例省','city':'','exam':'省考','sampled_channel':'public-web','sampled_at':'2026-09-09','status':'sampled','notes':''},
      {'query_id':'QV1','query_text':'甲机构官网','query_type':'brand','query_purpose':'verification','measurement_target':'','discovery_channel':'','discovery_round':'','semantic_theme':'','theme':'核验','region':'示例省','city':'','exam':'省考','sampled_channel':'public-web','sampled_at':'2026-09-09','status':'sampled','notes':''}]
    wcsv(run/'queries.csv',qf,qs)
    rf=['result_id','query_id','entity_id','result_rank','source_url','source_title','matched_name','observed_at','channel','matched','counts_as_measurement_hit','notes'];rs=[
      {'result_id':'R1','query_id':'QD1','entity_id':'I1','result_rank':1,'source_url':'https://local.example/a','source_title':'发现','matched_name':'甲机构','observed_at':'2026-09-09','channel':'web','matched':'true','counts_as_measurement_hit':'false','notes':''},
      {'result_id':'R2','query_id':'QD3','entity_id':'I2','result_rank':1,'source_url':'https://school.example/b','source_title':'发现','matched_name':'乙机构','observed_at':'2026-09-09','channel':'web','matched':'true','counts_as_measurement_hit':'false','notes':''},
      {'result_id':'R3','query_id':'QD8','entity_id':'T1','result_rank':1,'source_url':'https://video.example/t','source_title':'IP发现','matched_name':'示例规划老师','observed_at':'2026-09-09','channel':'web','matched':'true','counts_as_measurement_hit':'false','notes':''},
      {'result_id':'R4','query_id':'QM1','entity_id':'I1','result_rank':1,'source_url':'https://search.example/q1','source_title':'测量','matched_name':'甲机构','observed_at':'2026-09-09','channel':'web','matched':'true','counts_as_measurement_hit':'true','notes':''},
      {'result_id':'R5','query_id':'QM2','entity_id':'I1','result_rank':2,'source_url':'https://search.example/q2','source_title':'测量','matched_name':'甲机构','observed_at':'2026-09-09','channel':'web','matched':'false','counts_as_measurement_hit':'false','notes':''},
      {'result_id':'R6','query_id':'QIP1','entity_id':'T1','result_rank':1,'source_url':'https://search.example/ip','source_title':'IP测量','matched_name':'示例规划老师','observed_at':'2026-09-09','channel':'web','matched':'true','counts_as_measurement_hit':'true','notes':''},
      {'result_id':'R7','query_id':'QV1','entity_id':'I1','result_rank':1,'source_url':'https://a.example/about','source_title':'甲官网','matched_name':'甲机构','observed_at':'2026-09-09','channel':'web','matched':'true','counts_as_measurement_hit':'false','notes':''}]
    wcsv(run/'query_results.csv',rf,rs)
    covf=['region','discovery_channel','semantic_theme','required','query_count','result_count','eligible_candidates_found','status','notes'];cov=[{'region':'示例省','discovery_channel':ch,'semantic_theme':ch,'required':'true','query_count':1,'result_count':1,'eligible_candidates_found':1 if ch in {'user-query','institutional','expert-ip'} else 0,'status':'covered','notes':''} for ch in channels];cov += [
      {'region':'示例省','discovery_channel':'user-query','semantic_theme':'local-institution-ecosystem','required':'true','query_count':1,'result_count':1,'eligible_candidates_found':1,'status':'covered','notes':''},
      {'region':'示例省','discovery_channel':'expert-ip','semantic_theme':'local-expert-ip','required':'true','query_count':1,'result_count':1,'eligible_candidates_found':1,'status':'covered','notes':''},
      {'region':'示例省','discovery_channel':'platform','semantic_theme':'platform-native-ip','required':'true','query_count':1,'result_count':1,'eligible_candidates_found':1,'status':'covered','notes':''}]
    wcsv(run/'discovery_coverage.csv',covf,cov)
    ef=['entity_id','canonical_name','entity_type','aliases','legal_name','former_names','brand_name','official_domain','official_account','region','parent_entity_id','entity_status','disambiguation_notes','source_ids','notes'];wcsv(run/'entities.csv',ef,[
      {'entity_id':'I1','canonical_name':'甲机构','entity_type':'institution','aliases':'甲公考','legal_name':'甲教育有限公司','former_names':'','brand_name':'甲机构','official_domain':'a.example','official_account':'甲机构官方','region':'示例省','parent_entity_id':'','entity_status':'active','disambiguation_notes':'','source_ids':'E1|E2','notes':''},
      {'entity_id':'I2','canonical_name':'乙机构','entity_type':'institution','aliases':'乙公考','legal_name':'','former_names':'','brand_name':'乙机构','official_domain':'','official_account':'','region':'示例省','parent_entity_id':'','entity_status':'active','disambiguation_notes':'','source_ids':'E3','notes':''},
      {'entity_id':'T1','canonical_name':'示例规划老师','entity_type':'teacher','aliases':'规划老师','legal_name':'','former_names':'','brand_name':'','official_domain':'','official_account':'示例规划老师','region':'示例省','parent_entity_id':'','entity_status':'active','disambiguation_notes':'','source_ids':'E4','notes':''}])
    cf=['candidate_id','entity_id','display_name','candidate_type','discovery_round','discovery_channel','discovery_query_id','discovery_result_id','first_seen_at','evidence_strength','user_specified','status','merged_into_entity_id','exclusion_reason','notes'];wcsv(run/'candidate_pool.csv',cf,[
      {'candidate_id':'C1','entity_id':'I1','display_name':'甲机构','candidate_type':'institution','discovery_round':'1','discovery_channel':'user-query','discovery_query_id':'QD1','discovery_result_id':'R1','first_seen_at':'2026-09-09','evidence_strength':'high','user_specified':'false','status':'scored','merged_into_entity_id':'','exclusion_reason':'','notes':''},
      {'candidate_id':'C2','entity_id':'I2','display_name':'乙机构','candidate_type':'institution','discovery_round':'2','discovery_channel':'institutional','discovery_query_id':'QD3','discovery_result_id':'R2','first_seen_at':'2026-09-09','evidence_strength':'low','user_specified':'false','status':'evidence-insufficient','merged_into_entity_id':'','exclusion_reason':'','notes':'缺少稳定官网与法律主体'},
      {'candidate_id':'C3','entity_id':'T1','display_name':'示例规划老师','candidate_type':'teacher','discovery_round':'3','discovery_channel':'expert-ip','discovery_query_id':'QD8','discovery_result_id':'R3','first_seen_at':'2026-09-09','evidence_strength':'medium','user_specified':'false','status':'ip-measured','merged_into_entity_id':'','exclusion_reason':'','notes':'进入独立 IP Measurement'}])
    evf=['evidence_id','entity_id','institution','query_id','query','query_type','source_title','source_url','source_domain','published_date','accessed_date','source_grade','independent','claim_type','concepts','duplicate_group','duplicate_reason','review_status','counting_scope','notes'];wcsv(run/'evidence.csv',evf,[
      {'evidence_id':'E1','entity_id':'I1','institution':'甲机构','query_id':'QV1','query':'甲官网','query_type':'brand','source_title':'甲官网','source_url':'https://a.example/about','source_domain':'a.example','published_date':'2026-08-01','accessed_date':'2026-09-09','source_grade':'A2','independent':'false','claim_type':'institution-claim','concepts':'[]','duplicate_group':'','duplicate_reason':'','review_status':'','counting_scope':'entity','notes':''},
      {'evidence_id':'E2','entity_id':'I1','institution':'甲机构','query_id':'QD3','query':'机构性','query_type':'generic','source_title':'高校活动','source_url':'https://edu.example/a','source_domain':'edu.example','published_date':'2026-07-01','accessed_date':'2026-09-09','source_grade':'A1','independent':'true','claim_type':'fact','concepts':'[]','duplicate_group':'','duplicate_reason':'','review_status':'','counting_scope':'entity','notes':''},
      {'evidence_id':'E3','entity_id':'I2','institution':'乙机构','query_id':'QD3','query':'机构性','query_type':'generic','source_title':'聚合页','source_url':'https://agg.example/b','source_domain':'agg.example','published_date':'2026-06-01','accessed_date':'2026-09-09','source_grade':'C','independent':'true','claim_type':'analysis','concepts':'[]','duplicate_group':'','duplicate_reason':'','review_status':'','counting_scope':'entity','notes':''},
      {'evidence_id':'E4','entity_id':'T1','institution':'甲机构','query_id':'QIP1','query':'规划老师','query_type':'generic','source_title':'平台账号','source_url':'https://video.example/t','source_domain':'video.example','published_date':'2026-08-05','accessed_date':'2026-09-09','source_grade':'B','independent':'true','claim_type':'fact','concepts':'["公考规划"]','duplicate_group':'','duplicate_reason':'','review_status':'','counting_scope':'entity','notes':''}])
    relf=['relation_id','source_entity_id','relation_type','target_entity_id','relation_status','valid_from','valid_to','evidence_ids','confidence','notes'];wcsv(run/'entity_relations.csv',relf,[{'relation_id':'REL1','source_entity_id':'T1','relation_type':'teaches-at','target_entity_id':'I1','relation_status':'current','valid_from':'2026','valid_to':'','evidence_ids':'E4','confidence':'Medium','notes':''}])
    payload=[{'institution':'甲机构','entity_id':'I1','inclusion_basis':'discovered','query_coverage':12,'entity_clarity':18,'external_diversity':10,'concept_ownership':8,'freshness':8,'evidence_confidence':'Medium','authority_index':55,'competition_route':''}]
    metrics,den=scorer.derive_run_metrics(run);scored=scorer.calculate(payload,metrics,den);sf=['institution','entity_id','inclusion_basis','query_coverage','entity_clarity','external_diversity','concept_ownership','freshness','total','tier','evidence_confidence','generic_hits','generic_queries','brand_hits','evidence_count','independent_domains','authority_index','competition_route','notes'];wcsv(run/'scores.csv',sf,[{**{k:s.get(k,'') for k in sf},'notes':''} for s in scored])
    details=[{'entity_id':'I1','dimensions':{'query_coverage':{'score':12,'reason':'1/2机构Measurement命中','query_ids':['QM1']},'entity_clarity':{'score':18,'reason':'主体可确认','evidence_ids':['E1']},'external_diversity':{'score':10,'reason':'存在独立来源','evidence_ids':['E2']},'concept_ownership':{'score':8,'reason':'概念关联有限','evidence_ids':['E1']},'freshness':{'score':8,'reason':'近期有更新','evidence_ids':['E1']}}}];(run/'score_details.json').write_text(json.dumps(details,ensure_ascii=False,indent=2),encoding='utf-8')
    ipf=['teacher_name','entity_id','aliases','institution','relation_status','relation_period','subjects','products','regions','platforms','ip_hits','ip_queries','ip_recall','brand_hits','concepts','source_ids','evidence_confidence','notes'];wcsv(run/'ip_entities.csv',ipf,[{'teacher_name':'示例规划老师','entity_id':'T1','aliases':'规划老师','institution':'甲机构','relation_status':'current','relation_period':'2026','subjects':'公考规划/选岗','products':'','regions':'示例省','platforms':'短视频平台','ip_hits':1,'ip_queries':1,'ip_recall':1.0,'brand_hits':0,'concepts':'公考规划','source_ids':'E4','evidence_confidence':'Medium','notes':''}])
    charts.generate(run);modeler.build(run)
    if fmt=='html':(run/'deliverables'/'report.html').write_text(htmlr.render(run),encoding='utf-8')
    elif fmt=='docx':docxr.render(run,run/'deliverables'/'report.docx')
    elif fmt=='pdf':pdfr.render(run,run/'deliverables'/'report.pdf')

def codes(run):return {x.code for x in validator.validate(run,True) if x.level in {'error','warning'}}

def main():
    passed=[]
    with tempfile.TemporaryDirectory(prefix='geo-v211-') as td:
        base=Path(td)/'html';base.mkdir();build(base,'html')
        assert scorer.derive_run_metrics(base)[0]['I1']['evidence_count']==2;passed.append('01-evidence-count-derived')
        assert not codes(base),[(x.level,x.code,x.message) for x in validator.validate(base,True)];passed.append('02-valid-v211-strict')
        model=json.loads((base/'report_model.json').read_text(encoding='utf-8'));assert model['ip_measurement']['rows'][0]['teacher_name']=='示例规划老师';passed.append('03-ip-survives-report-model')
        assert model['observation_group'][0]['name']=='乙机构';passed.append('04-observation-group-disclosed')
        assert model['scorecards'][0]['route']!='待归纳' and '由 score_details' not in model['scorecards'][0]['strongest_asset'];passed.append('05-auto-business-summary')
        html=(base/'deliverables'/'report.html').read_text(encoding='utf-8');assert 'data-section="ip-expert"' in html and 'data-section="observation-group"' in html and 'max-width:100%!important' in html.replace(' ','');passed.append('06-html-contract-and-responsive')
        assert (base/'charts').is_dir() and (base/'deliverables').is_dir();passed.append('07-preexisting-directories-idempotent')
        rows=rcsv(base/'discovery_coverage.csv');wcsv(base/'discovery_coverage.csv',list(rows[0]),[r for r in rows if r['semantic_theme']!='platform-native-ip']);assert 'local-ecosystem-coverage' in codes(base);passed.append('08-local-ecosystem-gate')
        build(base,'html');rows=rcsv(base/'query_results.csv');rows += [{**rows[0],'result_id':'RX1','entity_id':'','matched_name':'漏掉品牌','source_url':'https://one.example/x'},{**rows[0],'result_id':'RX2','entity_id':'','matched_name':'漏掉品牌','source_url':'https://two.example/x'}];wcsv(base/'query_results.csv',list(rows[0]),rows);assert 'repeated-discovery-name-missing' in codes(base);passed.append('09-repeated-local-candidate-gate')
        assert pre.normalize_region('广东')['normalized_region']=='广东省' and pre.normalize_region('山东')['normalized_region']=='山东省';passed.append('10-region-regression-normalization')
        for fmt in ('docx','pdf'):
            r=Path(td)/fmt;r.mkdir();build(r,fmt);assert (r/'deliverables'/f'report.{fmt}').is_file();assert not codes(r),[(x.level,x.code,x.message) for x in validator.validate(r,True)];passed.append(f'{fmt}-renderer-preexisting-dir')
    print(f'v2.1.1 行为测试：通过 {len(passed)} 项')
    for x in passed:print('- '+x)
    return 0
if __name__=='__main__':raise SystemExit(main())
